version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: nmd-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nerves_metal_detector_dev
      - PGDATA=/var/lib/postgresql/data
    restart: always
